export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNOUT = 'SIGNOUT';

export const BRAND_INFO_REQUEST = 'BRAND_INFO_REQUEST';
export const BRAND_INFO_SUCCESS = 'BRAND_INFO_SUCCESS';
export const BRAND_INFO_FAILURE = 'BRAND_INFO_FAILURE';

export const BRAND_AND_IMAGES_REQUEST = 'BRAND_AND_IMAGES_REQUEST';
export const BRAND_AND_IMAGES_SUCCESS = 'BRAND_AND_IMAGES_SUCCESS';
export const BRAND_AND_IMAGES_FAILURE = 'BRAND_AND_IMAGES_FAILURE';

export const GALLERY_INFO_REQUEST = 'GALLERY_INFO_REQUEST';
export const GALLERY_INFO_SUCCESS = 'GALLERY_INFO_SUCCESS';
export const GALLERY_INFO_FAILURE = 'GALLERY_INFO_FAILURE';

export const REGISTER_ACCOUNT_REQUEST = 'REGISTER_ACCOUNT_REQUEST';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAILURE = 'REGISTER_ACCOUNT_FAILURE';